### ISSUE TITLE
[JOSS review] Pinning Pytorch

### ISSUE THREAD

**Issue by dionhaefner** [delve-team/delve#54]
Is it really necessary to pin Pytorch to `==1.9.0`? Seems quite restrictive to me, and makes the package harder to install (because if you e.g. do `pip install delve`  and then `pip install torchvision` it gets overwritten again).

(This is a part of the ongoing review at https://github.com/openjournals/joss-reviews/issues/3992)

**Comment by MLRichter** [comment]
Resolved in PR https://github.com/delve-team/delve/pull/62, waiting for approval.
