### ISSUE TITLE
[JOSS review] Incorrect qualifiers

### ISSUE THREAD

**Issue by dionhaefner** [delve-team/delve#55]
Qualifiers in `setup.py`:

```python
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
```

But since you have `python_requires='>=3.6'`, this should probably be something like `3.6` through `3.10`.

(This is a part of the ongoing review at openjournals/joss-reviews#3992)

**Comment by justinshenk** [comment]
Thanks! Fixed in https://github.com/delve-team/delve/commit/70b6ddb290622a1938cf4ea3bcf6da6c1b25d268, closing.
