### ISSUE TITLE
[JOSS review] API

### ISSUE THREAD

**Issue by dionhaefner** [delve-team/delve#58]
I wonder if `CheckLayerSat` is really the best name for your main tracker object. The imperative sounds more like a function name to me, and `Sat` is so overloaded that it's not obvious what it stands for. I would probably use something like `SaturationTracker` or so.

But I understand that changing names in the public API can be a pain, so if you insist to keep it that's fine with me.

(This is a part of the ongoing review at openjournals/joss-reviews#3992)

**Comment by MLRichter** [comment]
Hi, I agree, and I think changing it is a good Idea, since the bugfix is trivial.
This is currently implemented in PR as part of a code cleanup effort and waiting for approval.
https://github.com/delve-team/delve/pull/63
