### ISSUE TITLE
[JOSS review] Doc nitpicks

### ISSUE THREAD

**Issue by dionhaefner** [delve-team/delve#59]
Things I noticed while reading the docs:

- Spurious `indices and tables` link on the saturation page.
- If I understand correctly then `CheckLayerSat` is the only way your users should interact with the library. In this case there's no need to include anything else in the API reference. Just focus on the essential API and exclude internal objects.
- Broken link on top of Reference page.
- I think the home page of your documentation fills a similar role as the GitHub README, in being the first point of interaction for new users where you should put your best foot forward. Right now your README is a lot more polished, so why not just include the README in the documentation home page and save yourself the hassle of maintaining both separately? (E.g. by converting the README to rst, see [mpi4jax](https://github.com/mpi4jax/mpi4jax) where we use this pattern.)
- I would link more prominently to the integration with the tensorflow playground, which really does a great job of introducing the library! Love the gif.
- Links under "dependencies" are broken (and the whole section is unnecessary IMO).
- Emphasize more clearly what I should read to understand the theory behind Delve. You mention several papers but I think highlighting a specific one could be helpful.

(This is a part of the ongoing review at openjournals/joss-reviews#3992)

**Comment by justinshenk** [comment]
Thanks for the helpful suggestions! These are addressed in v0.1.49 with commits:
a273dbddce1bc631049ce1ec5b96e5df7329ef66
563c69ea4341884c405753d3b264c6c386109815
6ac1bebf7f49b96688c43742e296402c33cd840a
