### ISSUE TITLE
Idiomatic 1.0 code

### ISSUE THREAD

**Issue by stared** [delve-team/delve#8]
I see that there are quite a few constructions which are obsolete in Python 0.4+.

For example: `Variable`. Plus, it seems that `.to(device)` is the preferred method to keep transfer to GPU (or not, if not available).

**Comment by justinshenk** [comment]
Removed `Variables` and replaced `.cuda()` with `.to(device)` in example
scripts in e77ada9dd3d87da18ce73033b6fb8a25b6d3cd9e. Thanks for the
suggestion!

**Comment by stared** [comment]
Awesome!

I tend to use `.to` *always*, without `if`s. That way in makes code cleaner (at least to my eyes; yes, I now it can be subjective).

**Comment by justinshenk** [comment]
I agree that is cleaner. I unfortunately however get `AssertionError: Torch
not compiled with CUDA enabled` on my CPU-only machine if I remove the
`if`s.

**Comment by stared** [comment]
Try
```python
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
model = models.resnet50(pretrained=True).to(device)```
vide https://deepsense.ai/keras-vs-pytorch-avp-transfer-learning/.

Of course `.cuda()` will fail of non-CUDA machine.

**Comment by justinshenk** [comment]
Thanks for the suggestion! Example files updated
in 320130c5f1c0212bc6c417087d353ce1b3a6ecce.
